name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # runs once a day
  workflow_dispatch:        # lets you trigger it manually from the Actions tab
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Guru-Surya-Raja-J
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#0C4A6E&color_dots=#ebedf0,#bae6fd,#7dd3fc,#38bdf8,#0ea5e9
            dist/github-contribution-grid-snake-dark.svg?color_snake=#facc15&color_dots=#161b22,#0c4a6e,#0ea5e9,#38bdf8,#7dd3fc

      - name: Push snake animation to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
